### ISSUE TITLE
Thread pane selected line not highlighted when it does not have focus

### ISSUE THREAD

**Issue by davoper** [Vigilans/accountcolors#15]
Thread pane in the middle of the screen, where all of the messages are displayed, has no indication of which message (line) was selected once it loses focus, for example, by clicking on the message content or clicking outside Thunderbird window (so that Thunderbird whole window no longer has focus).

This makes it very difficult to know which message from a long list of messages in Thread pane is currently being viewed.

All of the check boxes / selections in accountcolors settings related to Thread Pane are disabled in this example.

However when only Thread Pane / Color Pane Background and Thread Pane / Color Background as Gradient are set, message row is mildly highlighted when focus is no longer on the thread pane.

Using TB v115.18.0 and accountcolors version TB115v3

**Comment by Vigilans** [comment]
Can reproduce in your setup.

I didn't experience this issue in my setting:
* Color Row Background
* Color based on Account of Received Email's Address
* Color Row Background as Label in Table View
* Color Row Background as Label in Card View

I notice that by disabling `Color Row Background as Label in Card View` the issue appears again. I'll propose a fix for it tomorrow.

**Comment by HankLloydRight** [comment]
Just wanted to add that I experienced this as well, but never had the time to type it all up and just lived with it.

Glad to hear a fix in on the way!  Thanks, @Vigilans!

**Comment by Vigilans** [comment]
New release with fix can be downloaded at https://github.com/Vigilans/accountcolors/releases/download/tb-115-v4/accountcolors.zip

Before the fix the issue will occur as long as `Color Row Background as Label in Card View` or `Color Row Background as Label in Table View` is disabled. This seems to have had a wide impact...

**Comment by HankLloydRight** [comment]
works great now, thank you again.

**Comment by davoper** [comment]
Works now, thanks!
