### ISSUE TITLE
Incoming Subject 

### ISSUE THREAD

**Issue by Devilwillcry4you** [Vigilans/accountcolors#2]
I am using thunderbird 115.7 and have no addons installed except this one. 

The incoming mail subject lines are not changing to the I specified in the addon settings. All the other choices changed except the colors  in the thread pane.

**Comment by Vigilans** [comment]
> The incoming mail subject lines are not changing to the I specified in the addon settings.

Which pane/window do you want to see the subject line colored? 

Can you provide a screenshot that annotates the area that does not get colored, and a screenshot of the font color / background you specify for your email address? (pixelate your private information)

> All the other choices changed except the colors in the thread pane.

You mean you enabled `Color Subject Font` in `Message Pane/Tab/Window` and `Compose Window`, but not `Thread Pane`?

**Comment by Devilwillcry4you** [comment]
Here is a screenshot, I outlined it in red. Yes the color subject font is checked in all available areas.


![blur1](https://github.com/Vigilans/accountcolors/assets/1855341/de2005cc-3f93-46d1-81f5-83de8add91e4)

**Comment by Devilwillcry4you** [comment]
I was able to get this to work playing around with the selections under the tools.
