### ISSUE TITLE
[Feature] Color gradients

### ISSUE THREAD

**Issue by MIOsystems** [Vigilans/accountcolors#4]
For an even more subtle and fine look it is effective to gradient the selected color to the default background color from left to right (or settable)

**Comment by Vigilans** [comment]
I personally prefer the label style so implemented it for myself. If you prefer the gradient style, you can take a look at this commit:
https://github.com/Vigilans/accountcolors/commit/502360b92fc754badc1714162c5c681fd8435e25:  Support coloring row background as label in thread pane.

It necessarily does all the things to introduce the label style feature:
* Core CSS and JS rendering logic.
* Preferences.
* Option in options page.
* Internationalization (Don't forget to add dtd entry to all dtd files!). 

The [core CSS rendering logic is](https://github.com/Vigilans/accountcolors/commit/502360b92fc754badc1714162c5c681fd8435e25#diff-a9dd570f22d9c695336f02a2b8a0a44e18b8a31d13b9202877cc712a15e4848dR169-R171):

https://github.com/Vigilans/accountcolors/blob/fe162d8ba2bf11b4ef4985d34c82c164a11c5fef/chrome/skin/accountcolors-about3pane.css#L207-L209

It is based on given `--ac-bkgd-color` and render it as `background-image` with `linear-gradient`. 

Seems your feature can exactly be interpreted as `linear-gradient`, so you can just implement the feature yourself and open a PR for it.

**Comment by MIOsystems** [comment]
I'm a little bit familiar with CSS. But simply have no idea how to implement it. I suggest just two boolean settings [Enable Gradient] and [Left or Right]. Then the gradient is composed with the account color and default background in a linear way. Alternatively there is a text field as setting and fill in the hole CSS code for that. Then we have the most customizability.

**Comment by Vigilans** [comment]
You can use `Ctrl + Shift + I` to open inspect tool, `Ctrl+Shift+C` and click on a row to select `<tr id=threadTree-row...>` element. 

On the right style pane, click `accountcolors-about3pane.css:...` to jump to the CSS source code. Then, in about line 203, modify `background-color` to `background-image` and `linear-gradient` with your preferred behavior.

By doing this you can test your preferred looking on the fly, and share your final CSS rule here.

**Comment by MIOsystems** [comment]
`background-image: linear-gradient(90deg, rgb(255, 233, 233) 0%, rgb(255, 255, 255) 100%);`

For the best impression i also add it to the `#threadPane > tree-view` Now it looks more like i would recommend.

![Gradient](https://github.com/Vigilans/accountcolors/assets/46918729/b96fd9ca-263f-47b0-95c7-c182520945ac)

**Comment by Vigilans** [comment]
Implemented in #8:
![](https://private-user-images.githubusercontent.com/20227484/304626275-94a398f1-489c-4da3-953d-298e34317e54.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4ODcxNjMsIm5iZiI6MTcwNzg4Njg2MywicGF0aCI6Ii8yMDIyNzQ4NC8zMDQ2MjYyNzUtOTRhMzk4ZjEtNDg5Yy00ZGEzLTk1M2QtMjk4ZTM0MzE3ZTU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDA1MDEwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmMmM1MmI2ZWU2OTNjNGVhMDNhZWM3NDA1YzU0ZWE4NDRjNmMyYjZkNWFlODQ2MTQ1MTRjOGFkOWNlY2E1NDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9hLUCivitqjTGKT_Ykn3Kw39aD15SpWHfLcpSGaKWeQ)

Download in https://github.com/Vigilans/accountcolors/releases/download/tb-115-v2/accountcolors.zip

**Comment by MIOsystems** [comment]
Your awesome. Works like a charm.
